apiVersion: v1
kind: Secret
metadata:
  name: intellica-secret
  namespace: intellica
type: Opaque
data:
  JWT_PASSWORD: dml2ZWtjaGF1ZGhhcmkxMjM0QHZpdmVrLmNvbQ==
  GROQ_API_KEY: <USER_GROQ_API_KEY_BASE64_HERE>
